# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  paths:
    include:
      - api-gateway/*

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  imageRepository: 'zakaryab2003/fsdevopsapi'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'image-registery'
        repository: 'zakaryab2003/fsdevopsapi'
        command: 'buildAndPush'
        Dockerfile: 'api-gateway/Dockerfile'
        buildContext: 'api-gateway/'
        tags: |
          $(tag)

- stage: Update
  displayName: Update
  jobs:
    - job: Update
      displayName: Update
      steps:
        - task: ShellScript@2
          inputs:
            scriptPath: 'Scripts/UpdateK8sManifests.sh'
            args: 'api-gateway $(imageRepository) $(tag)'
