services:
  user-service:
    image: zakaryab2003/fsdevopsuser:latest
    networks:
      - app-network

  order-service:
    image: zakaryab2003/fsdevopsorder:latest
    networks:
      - app-network
    environment:
      - INVENTORY_SERVICE_URL=http://inventory-service:3002
  
  inventory-service:
    image: zakaryab2003/fsdevopsinventory:latest  
    networks:
      - app-network
  
  api-gateway:
    image: zakaryab2003/fsdevopsapi:latest
    ports:
      - "8000:8000"
    networks:
      - app-network
    depends_on:
      - user-service
      - order-service
      - inventory-service
    environment:
      - ORDER_SERVICE_URL=http://order-service:3001
      - INVENTORY_SERVICE_URL=http://inventory-service:3002
      - USER_SERVICE_URL=http://user-service:3003

  frontend:
    image: zakaryab2003/fsdevopsfrontend:latest
    ports:
      - "80:80"
    networks:
      - app-network
    environment:
      - GATEWAY_URL=http://localhost:8000
    depends_on:
      - api-gateway

networks:
  app-network:
    driver: bridge