apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deploy
  namespace: sre-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/metrics'
        # --- FIX #1 ---
        # Update prometheus port
        prometheus.io/port: '8000'
    spec:
      containers:
        - name: api-gateway
          # Make sure this is your correct image
          image: zakaryab2003/fsdevopsapi:70
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: ORDER_SERVICE_URL
              value: "http://order-service-svc.sre-lab:3001"
            - name: INVENTORY_SERVICE_URL
              value: "http://inventory-service-svc.sre-lab:3002"
            - name: USER_SERVICE_URL
              value: "http://user-service-svc.sre-lab:3003"
            - name: OTEL_SERVICE_NAME
              value: "api-gateway"
            - name: OTEL_EXPORTER_JAEGER_ENDPOINT
              value: "http://jaeger-all-in-one.tracing.svc.cluster.local:14268/api/traces"
          
          livenessProbe:
            httpGet:
              path: /healthz
              # --- FIX #3 ---
              # Update liveness probe port
              port: 8000
            # Give the container 30 seconds to start before liveness check
            initialDelaySeconds: 30
            periodSeconds: 10
          
          readinessProbe:
            httpGet:
              path: /healthz
              # --- FIX #4 ---
              # Update readiness probe port
              port: 8000
            # Give the container 15 seconds to be "ready"
            initialDelaySeconds: 15
            periodSeconds: 5
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"